### ISSUE TITLE
The dataset link is not available 

### ISSUE THREAD

**Issue by icupsy** [canlab/2017_kragel_mfc_generalizability_natneurosci#1]
Hi,
Thanks for sharing the code and dataset. 

I want to test the code but the link for downloading data is not working. Could you help me with that, thank you!

Xin

**Comment by torwager** [comment]
Hi Xin,

It’s on Neurovault, #3324, e.g., 

  Download images from Kragel et al. 2018 Nature Neuroscience
  Kragel, P. A., Kano, M., Van Oudenhove, L., Ly, H. G., Dupont, P., Rubio, A., ? Wager, T. D. (2018). 
  Generalizable representations of pain, cognitive control, and negative emotion in medial frontal cortex. 
  Nature Neuroscience, 21(2), 283?289. doi:10.1038/s41593-017-0051-7 
  
  270 subject-level images systematically sampled from 18 studies across 3 domains
  [files_on_disk, url_on_neurovault, mycollection, myimages] = retrieve_neurovault_collection(3324);
  data_obj = fmri_data(files_on_disk)

Best wishes,
Tor
____________________________________
Tor Wager
Diana L. Taylor Distinguished Professor
Presidential Cluster in Neuroscience and 
Department of Psychological and Brain Sciences
Dartmouth College
___________________________________

**Comment by icupsy** [comment]
Wow, thanks for the details! It helps a lot!

Best,
Xin
